/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Estimate {
  'projectType' : ProjectType,
  'estimatedCost' : bigint,
}
export type ProjectId = bigint;
export interface ProjectType {
  'aiIntegration' : boolean,
  'website' : boolean,
  'automation' : boolean,
  'mobileApp' : boolean,
  'ecommerce' : boolean,
}
export interface _SERVICE {
  'createProjectType' : ActorMethod<
    [boolean, boolean, boolean, boolean, boolean],
    bigint
  >,
  'estimateProject' : ActorMethod<[ProjectType], bigint>,
  'getAllEstimates' : ActorMethod<[], Array<Estimate>>,
  'getAllProjectTypes' : ActorMethod<[], Array<ProjectType>>,
  'getEstimate' : ActorMethod<[ProjectId], Estimate>,
  'getProjectType' : ActorMethod<[ProjectId], ProjectType>,
  'updateProjectType' : ActorMethod<
    [ProjectId, boolean, boolean, boolean, boolean, boolean],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];