/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectType = IDL.Record({
  'aiIntegration' : IDL.Bool,
  'website' : IDL.Bool,
  'automation' : IDL.Bool,
  'mobileApp' : IDL.Bool,
  'ecommerce' : IDL.Bool,
});
export const Estimate = IDL.Record({
  'projectType' : ProjectType,
  'estimatedCost' : IDL.Nat,
});
export const ProjectId = IDL.Nat;

export const idlService = IDL.Service({
  'createProjectType' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'estimateProject' : IDL.Func([ProjectType], [IDL.Nat], []),
  'getAllEstimates' : IDL.Func([], [IDL.Vec(Estimate)], ['query']),
  'getAllProjectTypes' : IDL.Func([], [IDL.Vec(ProjectType)], ['query']),
  'getEstimate' : IDL.Func([ProjectId], [Estimate], ['query']),
  'getProjectType' : IDL.Func([ProjectId], [ProjectType], ['query']),
  'updateProjectType' : IDL.Func(
      [ProjectId, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectType = IDL.Record({
    'aiIntegration' : IDL.Bool,
    'website' : IDL.Bool,
    'automation' : IDL.Bool,
    'mobileApp' : IDL.Bool,
    'ecommerce' : IDL.Bool,
  });
  const Estimate = IDL.Record({
    'projectType' : ProjectType,
    'estimatedCost' : IDL.Nat,
  });
  const ProjectId = IDL.Nat;
  
  return IDL.Service({
    'createProjectType' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'estimateProject' : IDL.Func([ProjectType], [IDL.Nat], []),
    'getAllEstimates' : IDL.Func([], [IDL.Vec(Estimate)], ['query']),
    'getAllProjectTypes' : IDL.Func([], [IDL.Vec(ProjectType)], ['query']),
    'getEstimate' : IDL.Func([ProjectId], [Estimate], ['query']),
    'getProjectType' : IDL.Func([ProjectId], [ProjectType], ['query']),
    'updateProjectType' : IDL.Func(
        [ProjectId, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool, IDL.Bool],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };